service: ${self:custom.name}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2

plugins:
  - serverless-nextjs-plugin
  - serverless-domain-manager

custom:
  name: resume
  serverless-nextjs:
    assetsBucketName: 'resume-assets-${self:provider.stage}'
  customDomain:
    ${file(./serverless.${self:provider.stage}.yml):custom.customDomain}

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**